### ISSUE TITLE
Update to Plone 6.0.7 and 5.2.14

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/demo.plone.org#25]
Could you update the demo sites to today's releases, please?
And probably a new Volto release as well.
Thanks!

**Comment by mauritsvanrees** [comment]
Or update to Plone 6.0.8, which is out today. :-)

**Comment by pbauer** [comment]
Fixed with https://github.com/plone/demo.plone.org/pull/27

**Comment by mauritsvanrees** [comment]
I confirm that the live sites have been updated.  Thanks!
