### ISSUE TITLE
Create volto.demo.plone.org which demo's a core Volto setup of Plone 

### ISSUE THREAD

**Issue by fredvd** [plone/demo.plone.org#40]
As discussed at Volto Team meeting 2024-04-23.  To reference issues to core Volto a separate demo distribution with only Core volto activated is useful to referende in issues, bug reports and discussions.

**Comment by fredvd** [comment]
Workin on it in https://github.com/plone/demo.plone.org/pull/41

**Comment by fredvd** [comment]
@ichim-david @sneridagh  I'm almost there, did some work on this during the beethoven sprint. To keep things uniform in all our demo's I will add plone.distribution to the 'core volto' backend as well  to scaffold the homepage, but we shouldn't add any other add'ons.  volto.demo.plone.org is already up and running.  It's just scaffolding wrong content/outdated content using setup handlers etc.

**Comment by ichim-david** [comment]
@fredvd Thank you for your work.

I am looking at the https://plone.org/try-plone and the screenshot for the demo site is wrong, it's for the volto basic site.
![classic-vs-demo](https://github.com/plone/demo.plone.org/assets/152852/5272246d-353c-4ee5-9df0-b2201852aad7)

Given the fact that classic is just classic and we have this volto stock site that we are getting back I think that this news should have information about all 3 demo sites (stock volto, stock classic, "marketing plone(volto) demo").

This information will be useful I think if newcomers want to add bug reports to Volto and they need the link to the testing website in order to show how to reproduce it.

**Comment by stevepiercy** [comment]
When it is ready, we also need to update documentation under [Try a Plone demo](https://6.docs.plone.org/install/index.html#try-a-plone-demo).

**Comment by ichim-david** [comment]
> @ichim-david @sneridagh I'm almost there, did some work on this during the beethoven sprint. To keep things uniform in all our demo's I will add plone.distribution to the 'core volto' backend as well to scaffold the homepage, but we shouldn't add any other add'ons. volto.demo.plone.org is already up and running. It's just scaffolding wrong content/outdated content using setup handlers etc.

@fredvd it's not just that, https://volto.demo.plone.org/image-test is using the same backend as demo.plone.org
I tried to upload an image here and it can't view it https://volto.demo.plone.org/aditional-equipment.png/@@images/image-200-f268ec11b5a1ffd12053a74aa0671999.png
If I go to demo https://demo.plone.org/image-test I see the image here.
Removing the volto from the url also displays it confirming that it uses the backend from demo.plone.org

**Comment by fredvd** [comment]
| @fredvd it's not just that, https://volto.demo.plone.org/image-test is using the same backend as demo.plone.org

You're right, i checked myself by creating a document. I didn't understand why, the RAZZLE_INTERNAL_API_PATH was set correctly, but I found my mistake later:  the router for the /++api++/ was in traefik was using the wrong backend. that's why rehydration after the initial page load from server side rendering flashed the site to the other content. 

I have updated the sites and we now have a 'normal' volto.demo.plone.org. 

What I still would like to add is a plone.distribution setup for the plain volto backend so we can add some more content on the homepage and explain the purpose of the site.  Not to add any other content types, but plone.distribution is 'go to' solution we now have. 

There is another ongoing issue that the site content is not properly refreshed, which is documented/discussed here: 
https://github.com/plone/demo.plone.org/issues/46

I had to remove the stack first and then redeploy to see the fix for the /++api++/ backend

**Comment by stevepiercy** [comment]
Would someone please update the list of demos? I can't keep track of them all.

https://6.docs.plone.org/install/index.html#try-a-plone-demo

AFAIK, only two are official demos.
